//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLoremipsu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBDSEntities : DbContext
    {
        public QLBDSEntities()
            : base("name=QLBDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<feature> features { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<listing_type> listing_type { get; set; }
        public virtual DbSet<property> properties { get; set; }
        public virtual DbSet<property_employee> property_employee { get; set; }
        public virtual DbSet<property_feature> property_feature { get; set; }
        public virtual DbSet<property_location> property_location { get; set; }
        public virtual DbSet<property_status> property_status { get; set; }
        public virtual DbSet<property_type> property_type { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
