//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLoremipsu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public property()
        {
            this.images = new HashSet<image>();
            this.property_employee = new HashSet<property_employee>();
            this.property_feature = new HashSet<property_feature>();
            this.reviews = new HashSet<review>();
        }
    
        public int property_id { get; set; }
        public string description { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> created_date { get; set; }
        public string address { get; set; }
        public Nullable<int> property_size { get; set; }
        public Nullable<int> num_bedrooms { get; set; }
        public Nullable<int> num_bathrooms { get; set; }
        public Nullable<int> num_carspaces { get; set; }
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<int> price { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> listing_id { get; set; }
        public Nullable<int> location_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
        public virtual listing_type listing_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_employee> property_employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<property_feature> property_feature { get; set; }
        public virtual property_location property_location { get; set; }
        public virtual property_status property_status { get; set; }
        public virtual property_type property_type { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
    }
}
