//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLoremipsu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class property_feature
    {
        public int idPF { get; set; }
        public int property_id { get; set; }
        public int feature_id { get; set; }
    
        public virtual feature feature { get; set; }
        public virtual property property { get; set; }
    }
}
