//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectLoremipsu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int review_id { get; set; }
        public string description { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> property_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual property property { get; set; }
        public virtual user user { get; set; }
    }
}
